CREATE TABLE IF NOT EXISTS analysis_tasks (
    task_id VARCHAR(36) NOT NULL,
    trace_id VARCHAR(36) NOT NULL,
    media_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    mode VARCHAR(32) NOT NULL,
    content_hash VARCHAR(128) NOT NULL,
    goal_digest VARCHAR(64) NOT NULL,
    user_goal VARCHAR(500) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_stage VARCHAR(64) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    error_type VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    submitted_at TIMESTAMP(3) NOT NULL,
    queued_at TIMESTAMP(3) NULL,
    started_at TIMESTAMP(3) NULL,
    finished_at TIMESTAMP(3) NULL,
    next_retry_at TIMESTAMP(3) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    active_key VARCHAR(255) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (task_id),
    UNIQUE KEY uk_analysis_tasks_active (active_key),
    KEY idx_analysis_tasks_media_goal (media_id, goal_digest, updated_at),
    KEY idx_analysis_tasks_user_time (user_id, updated_at),
    KEY idx_analysis_tasks_recovery (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
